export const EnvKeys = {
  ENV_PORT: 'PORT',
  ENV_DB_PG_USERNAME: 'DB_PG_USERNAME',
  ENV_DB_PG_PASSWORD: 'DB_PG_PASSWORD',
  ENV_DB_PG_HOST: 'DB_PG_HOST',
  ENV_DB_PG_PORT: 'DB_PG_PORT',
  ENV_DB_PG_DATABASE: 'DB_PG_DATABASE',
};
