services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_PG_USERNAME}
      POSTGRES_PASSWORD: ${DB_PG_PASSWORD}
      POSTGRES_DB: ${DB_PG_DATABASE}
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - ./redis-data:/data
